#ifndef EXPONENT_HPP_INCLUDED
#define EXPONENT_HPP_INCLUDED

/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

namespace mathworks
{
namespace exponent
{
//! Gets the square of the number.
/*! @param base The base to square.
   @return The square of the numbers.
*/
int square(int base);
//! Gets the square of the number.
/*! @param base The base to square.
  @return The square of the numbers.
*/
double square(double base);
//! Gets the cube of the number.
/*! @param base The base to cube.
  @return The cube of the numbers.
*/
int cube(int base);
//! Gets the cube of the number.
/*! @param base The base to cube.
 @return The cube of the numbers.
*/
double cube(double base);
//! Raises a number to a power.
/*! @param base The base.
 @param power The power to raise "base" to.
 @return The result of the calculation.
*/
int calc(int base, int power);
//! Raises a number to a power.
/*! @param base The base.
 @param power The power to raise "base" to.
 @return The result of the calculation.
*/
double calc(double base, int power);
}
}

#endif // EXPONENT_HPP_INCLUDED
