#ifndef SHAPES_HPP_INCLUDED
#define SHAPES_HPP_INCLUDED

/*
Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

/*! \mainpage Welcome to Mathworks++!
 Mathworks++ is a C++ port of Python mathworks.
*/

class square
{
public:
    square();
    void setLength(double length);
    double getLength();
    double getPerimeter();
    double getArea();
private:
    double length;
    double perimeter;
    double area;
};

class rectangle
{
public:
    rectangle();
    void setLength(double length);
    double getLength();
    void setWidth(double width);
    double getWidth();
    double getPerimeter();
    double getArea();
private:
    double length;
    double width;
    double perimeter;
    double area;
};

class circle
{
public:
    circle();
    void setRadius(double newradius);
    void setDiameter(double newdiam);
    double getRadius();
    double getDiameter();
    double getCircumference();
    double getArea();
private:
    double radius;
    double diameter;
    double circumference;
    double area;
};

class triangle
{
public:
    triangle();
    void setSide(int side, double length);
    double getSide(int sidenum);
    void setBase(double value);
    double getBase();
    void setHeight(double value);
    double getHeight();
    double getPerimeter();
    double getArea();
    void setAngle(int anglenum, double measure);
    double getAngle(int anglenum);
private:
    double side[3];
    double angle[3];
    double perimeter;
    double area;
    double base;
    double height;
};

#endif // SHAPES_HPP_INCLUDED
